ktor:
  deployment:
    port: 8080
  application:
    startup: sequential
    modules:
      - com.example.ApplicationKt.installCore
      - com.example.ApplicationKt.installPlugins
      - com.example.ApplicationKt.installRouting
      - com.example.ApplicationKt.installLifecycle
