package com.example.infrastructure.content

import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.runBlocking
import java.awt.Color
import java.awt.image.BufferedImage
import java.io.ByteArrayOutputStream
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class ImagePreprocessorTest {
    private val preprocessor = ImagePreprocessor()
    private val planeSize = ImagePreprocessor.TARGET_SIZE * ImagePreprocessor.TARGET_SIZE

    @Test
    fun `JPEG decodes to (3, 224, 224) tensor with channel stats in ImageNet-normalized range`() {
        runBlocking {
            val bytes = encode(makeGradient(300, 200), "jpeg")
            val out = preprocessor.preprocess(bytes)
            assertEquals(3 * planeSize, out.size)
            assertChannelStatsPlausible(out)
        }
    }

    @Test
    fun `PNG decodes to (3, 224, 224) tensor with channel stats in ImageNet-normalized range`() {
        runBlocking {
            val bytes = encode(makeGradient(180, 320), "png")
            val out = preprocessor.preprocess(bytes)
            assertEquals(3 * planeSize, out.size)
            assertChannelStatsPlausible(out)
        }
    }

    @Test
    fun `broken bytes raise IllegalArgumentException, no JVM crash`() {
        runBlocking {
            val bogus = byteArrayOf(0x42, 0x4F, 0x47, 0x55, 0x53)
            assertFailsWith<IllegalArgumentException> { preprocessor.preprocess(bogus) }
        }
    }

    @Test
    fun `concurrent preprocess calls produce equal results for equal inputs`() {
        runBlocking {
            val bytes = encode(makeGradient(400, 400), "png")
            val expected = preprocessor.preprocess(bytes)
            val outputs =
                coroutineScope {
                    (1..10).map { async { preprocessor.preprocess(bytes) } }.awaitAll()
                }
            outputs.forEach { o -> assertTrue(o.contentEquals(expected), "concurrent result diverged") }
        }
    }

    @Test
    fun `output matches Pillow LANCZOS reference within float tolerance`() {
        runBlocking {
            // Fixture generated by scripts/gen_lanczos_fixture.py:
            // 19x13 deterministic gradient encoded as PNG, resized via
            // Pillow LANCZOS to 224x224, ImageNet-normalized in CHW.
            // Reading the same PNG bytes through ImageIO ensures we and
            // Pillow start from byte-identical input.
            val inputBytes = loadResource("/fixtures/lanczos_input.png")
            val expected = loadFloatArray("/fixtures/lanczos_expected.bin")
            val actual = preprocessor.preprocess(inputBytes)

            assertEquals(expected.size, actual.size)
            // Tolerance accounts for float32 rounding differences between
            // Java's Math.sin and CPython's libm — both use the same IEEE
            // semantics, so divergence is at the last few mantissa bits.
            val tolerance = 1e-3f
            var maxDiff = 0f
            for (i in expected.indices) {
                val diff = kotlin.math.abs(expected[i] - actual[i])
                if (diff > maxDiff) maxDiff = diff
            }
            assertTrue(maxDiff <= tolerance, "Max divergence from Pillow LANCZOS = $maxDiff > $tolerance")
        }
    }

    private fun assertChannelStatsPlausible(tensor: FloatArray) {
        // Each plane should sit roughly in the ImageNet-normalized range
        // [-2.2, 2.7] (worst case: pixel=0 or pixel=255 against mean/std).
        for (c in 0 until 3) {
            var min = Float.POSITIVE_INFINITY
            var max = Float.NEGATIVE_INFINITY
            for (i in 0 until planeSize) {
                val v = tensor[c * planeSize + i]
                if (v < min) min = v
                if (v > max) max = v
            }
            assertTrue(min >= -2.2f, "plane $c min=$min below ImageNet range")
            assertTrue(max <= 2.7f, "plane $c max=$max above ImageNet range")
        }
    }

    private fun makeGradient(
        w: Int,
        h: Int,
    ): BufferedImage {
        val img = BufferedImage(w, h, BufferedImage.TYPE_INT_RGB)
        for (y in 0 until h) {
            for (x in 0 until w) {
                val r = (255 * x / w).coerceIn(0, 255)
                val g = (255 * y / h).coerceIn(0, 255)
                val b = (255 - (255 * (x + y) / (w + h))).coerceIn(0, 255)
                img.setRGB(x, y, Color(r, g, b).rgb)
            }
        }
        return img
    }

    private fun encode(
        img: BufferedImage,
        format: String,
    ): ByteArray =
        ByteArrayOutputStream().use {
            ImageIO.write(img, format, it)
            it.toByteArray()
        }

    private fun loadResource(path: String): ByteArray =
        ImagePreprocessorTest::class.java.getResourceAsStream(path)?.readBytes()
            ?: error("Test resource not found: $path")

    private fun loadFloatArray(path: String): FloatArray {
        val bytes = loadResource(path)
        require(bytes.size % 4 == 0) { "Resource $path size is not a multiple of 4" }
        val buffer =
            java.nio.ByteBuffer
                .wrap(bytes)
                .order(java.nio.ByteOrder.LITTLE_ENDIAN)
        return FloatArray(bytes.size / 4) { buffer.float }
    }
}
